# Generated by Django 2.2.5 on 2019-09-04 07:25

from django.db import migrations, models

import imagebkd.fileutils
import imagebkd.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagebkd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='outputFile',
        ),
        migrations.AddField(
            model_name='output',
            name='outputFilePath',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='input',
            field=models.ImageField(upload_to=imagebkd.fileutils.determineUpload),
        ),
        migrations.AlterField(
            model_name='output',
            name='outputStr',
            field=models.TextField(default='处理中...'),
        ),
    ]
