# Generated by Django 2.2.5 on 2019-09-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagebkd', '0003_auto_20190906_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='process',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
