# Generated by Django 2.2.5 on 2019-09-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagebkd', '0004_output_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputfile',
            name='input',
            field=models.ImageField(upload_to=''),
        ),
        migrations.CreateModel(
            name='MoreOutputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.TextField()),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagebkd.Output')),
            ],
        ),
    ]
